-- the club data at the start of the season
INSERT INTO members (email, firstName, lastName) VALUES ('maya.thompson@example.com', 'Maya', 'Thompson');
INSERT INTO members (email, firstName, lastName) VALUES ('ava.lopez@example.com', 'Ava', 'Lopez');
INSERT INTO members (email, firstName, lastName) VALUES ('ben.okafor@example.com', 'Ben', 'Okafor');
INSERT INTO members (email, firstName, lastName) VALUES ('cam.nguyen@example.com', 'Cam', 'Nguyen');
INSERT INTO members (email, firstName, lastName) VALUES ('dev.patel@example.com', 'Dev', 'Patel');
INSERT INTO members (email, firstName, lastName) VALUES ('elena.rossi@example.com', 'Elena', 'Rossi');
INSERT INTO members (email, firstName, lastName) VALUES ('farah.haddad@example.com', 'Farah', 'Haddad');
INSERT INTO members (email, firstName, lastName) VALUES ('gabe.martinez@example.com', 'Gabe', 'Martinez');
INSERT INTO members (email, firstName, lastName) VALUES ('hana.kim@example.com', 'Hana', 'Kim');
INSERT INTO members (email, firstName, lastName) VALUES ('isaac.cohen@example.com', 'Isaac', 'Cohen');
INSERT INTO members (email, firstName, lastName) VALUES ('jordan.lee@example.com', 'Jordan', 'Lee');
INSERT INTO members (email, firstName, lastName) VALUES ('keisha.brown@example.com', 'Keisha', 'Brown');
INSERT INTO slots (id, date, task, start, end, capacity) VALUES (1, '2027-06-05', 'watering', '08:00', '09:00', 2);
INSERT INTO slots (id, date, task, start, end, capacity) VALUES (2, '2027-06-05', 'harvesting', '09:00', '11:00', 3);
INSERT INTO slots (id, date, task, start, end, capacity) VALUES (3, '2027-06-12', 'watering', '08:00', '09:00', 2);
INSERT INTO slots (id, date, task, start, end, capacity) VALUES (4, '2027-06-12', 'weeding', '09:00', '11:00', 4);
INSERT INTO slots (id, date, task, start, end, capacity) VALUES (5, '2027-06-19', 'watering', '08:00', '09:00', 2);
INSERT INTO slots (id, date, task, start, end, capacity) VALUES (6, '2027-06-19', 'planting', '09:00', '11:00', 3);
INSERT INTO slots (id, date, task, start, end, capacity) VALUES (7, '2027-06-26', 'watering', '08:00', '09:00', 2);
INSERT INTO slots (id, date, task, start, end, capacity) VALUES (8, '2027-06-26', 'harvesting', '09:00', '11:00', 3);
INSERT INTO slotSignups (id, slotId, memberEmail, cancelCode) VALUES (1, 1, 'hana.kim@example.com', lower(hex(randomblob(16))));
INSERT INTO slotSignups (id, slotId, memberEmail, cancelCode) VALUES (2, 1, 'farah.haddad@example.com', lower(hex(randomblob(16))));
INSERT INTO slotSignups (id, slotId, memberEmail, cancelCode) VALUES (3, 2, 'ava.lopez@example.com', lower(hex(randomblob(16))));
INSERT INTO slotSignups (id, slotId, memberEmail, cancelCode) VALUES (4, 3, 'keisha.brown@example.com', lower(hex(randomblob(16))));
INSERT INTO slotSignups (id, slotId, memberEmail, cancelCode) VALUES (5, 4, 'dev.patel@example.com', lower(hex(randomblob(16))));
INSERT INTO slotSignups (id, slotId, memberEmail, cancelCode) VALUES (6, 4, 'keisha.brown@example.com', lower(hex(randomblob(16))));
INSERT INTO slotSignups (id, slotId, memberEmail, cancelCode) VALUES (7, 5, 'maya.thompson@example.com', lower(hex(randomblob(16))));
INSERT INTO slotSignups (id, slotId, memberEmail, cancelCode) VALUES (8, 5, 'ben.okafor@example.com', lower(hex(randomblob(16))));
INSERT INTO slotSignups (id, slotId, memberEmail, cancelCode) VALUES (9, 7, 'ben.okafor@example.com', lower(hex(randomblob(16))));
INSERT INTO slotSignups (id, slotId, memberEmail, cancelCode) VALUES (10, 8, 'keisha.brown@example.com', lower(hex(randomblob(16))));
INSERT INTO slotSignups (id, slotId, memberEmail, cancelCode) VALUES (11, 8, 'hana.kim@example.com', lower(hex(randomblob(16))));
INSERT INTO slotSignups (id, slotId, memberEmail, cancelCode) VALUES (12, 8, 'gabe.martinez@example.com', lower(hex(randomblob(16))));
